services:
  - type: web
    name: Web-scraper
    env: python
    plan: free
    buildCommand: |
      chmod +x install_chrome.sh
      ./install_chrome.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120

